### ISSUE TITLE
Support for WWW.

### ISSUE THREAD

**Issue by Magallanesmapping321** [richardg867/WaybackProxy#18]
I dont know if its only me but most links in web.archive.org sites are in www, example: youtube in 2005-2012, but when i open a website with HTTPS or WWW, it doesnt work, could you please fix this?

K thats all

UPDATE: Nevermind, it was a issue with chrome

**Comment by Magallanesmapping321** [comment]
Apparently www.google.com works :/, probably detects www as a subdomain

**Comment by Magallanesmapping321** [comment]
Nevermind

**Comment by richardg867** [comment]
Using WaybackProxy with a modern browser can result in HSTS shenanigans, where the original website may try to force TLS but WaybackProxy can't handle that.
