### ISSUE TITLE
web.archive.org settings dont work

### ISSUE THREAD

**Issue by ultimatexilliam** [richardg867/WaybackProxy#2]
![image](https://user-images.githubusercontent.com/78660109/166477698-b05dd50c-59bf-4eb8-b89d-92984cce3557.png)
 
Running on Raspberry Pi 3 Model B+, OS: Ubuntu 20.04.4 LTS,  WebBrowser:RetroZilla

**Comment by jmarler** [comment]
The pull request that I just submitted fixes this and a few other bugs.
