### ISSUE TITLE
YouTube does not like the proxy in IE11 + Archive Finding The Correct Dates

### ISSUE THREAD

**Issue by RealEMK** [richardg867/WaybackProxy#20]
I have the date set to October 31 2005.
I type in http://www.youtube.com and it immediately doesn't load, citing "HTTP 501 Not Implemented/HTTP 505 Version Not Supported".

When trying to load a page like RuneScape, it will load a page from years earlier.

When loading Google.com it works just fine, but when I type YouTube into the search box and press Search, it says there are no snapshots within the date range in my config. I had it set to 365, and tried updating it to 500 but that didn't fix the problem.

**Comment by richardg867** [comment]
Failed to reproduce any of this. Google and anything else server-side not working is fully expected.
