### ISSUE TITLE
Really old browsers aren't happy with the inserted Javascript

### ISSUE THREAD

**Issue by misterblack1** [richardg867/WaybackProxy#24]
Hi, I setup Waybackproxy on a Docker container and while it's service up pages from the date specified, it seems to insert some JS at the start which is breaking things on IE 5 and Netscape 3. (The two browsers I tried on Windows 98 and Mac OS 7.5.3 respectively.)

I looked through the docs I don't immediately see a way to stop this JS insertion -- and I missing a config option?

Thanks!

**Comment by richardg867** [comment]
The container uploaded to Docker Hub is maintained by a community contributor, who hasn't updated it after a recent fix I made to address a change on the Wayback Machine's end. I recommend doing a local build instead.

**Comment by richardg867** [comment]
Nevermind that, I found another JavaScript patching issue and corrected it. The recommendation to use a local build still stands.
