### ISSUE TITLE
Moron, Cant Figure it Out

### ISSUE THREAD

**Issue by MoronNeedsHelp** [richardg867/WaybackProxy#26]
I don't understand how to get this running on Windows. Whenever I open the proxy, it just closes instantly. What moronic thing am I doing wrong?

**Comment by celguar** [comment]
Updated requirements to match latest version

**Comment by MoronNeedsHelp** [comment]
Figured it out.

**GUIDE for Win10**

download and install python

run "ipconfig" in command prompt, take note of the ipv4 address

open cmd with admin, type "cd (the unzipped folder)"

type "waybackproxy.py"

open Settings > Network > Proxy

use setup script, use the autoconfig url to the open given in readme: "http://ip:port/proxy.pac" make sure "ip" is the ipv4 we found with ipconfig, and make the "port" 8888

Open browser, type the http address of the site you are looking for

**Done!**

MoronFiguredItOut

**Comment by celguar** [comment]
can just double click on .py file I think
