### ISSUE TITLE
Netscape Communicator - WaybackProxy only implments the GET method

### ISSUE THREAD

**Issue by ross-ns** [richardg867/WaybackProxy#34]
Trying out Netscape Communicator versions 4.73 and 4.79 on Windows 98. Both versions return the error "WaybackProxy only implements the GET method". I can confirm that my setup is good as Internet Explorer 6 on the same machine works fine.

I presume this is because Netscape uses POST but I'm not able to confirm that.

**Comment by richardg867** [comment]
While I failed to reproduce the issue myself with these Netscape versions on Windows 98 SE, I suspect they're somehow sending a lowercase HTTP GET. Please reopen the issue if it wasn't fixed; the error page should have more details now too.
