### ISSUE TITLE
If your all YouTube video link been deleted, You need to use some how to saved the deleted YouTube video link to past with wayback proxy.

### ISSUE THREAD

**Issue by akpmast2007** [richardg867/WaybackProxy#7]
Hi, if the YouTube video have been deleted, And the video link is not saved from past.
Here it is.
1. Type https://www.youtube.com/watch?v= to wayback machine.
2. Go to Twitter to find the link and copy the link.
3. Paste the link to wayback machine.
4. Save your video to past and future.
5. And enjoy your video using wayback proxy.

**Comment by richardg867** [comment]
Closing as unintelligible and quite possibly off-topic.
