### ISSUE TITLE
Config doesn't even work

### ISSUE THREAD

**Issue by jlnhlfan** [richardg867/WaybackProxy#8]
![Screenshot_May_20_2022_08_51_14_AM](https://user-images.githubusercontent.com/31529087/169565564-ca2336d5-0cfb-4da2-a552-7dc847e46a3f.png)

I'd love to use this for browsing the NHL's website as it looked in the late 1990s and early 2000s... if config.py even worked! As you can see in the screenshot I have put in this issue, config won't even open because of a syntax error in line 1, resulting in me not really being able to change any sort of settings. What can I do in this situation?

**Comment by radiocolin** [comment]
You're trying to paste the path of a file into the python IDE, not sure what you're trying to do here. Edit the config.py file in a text editor, then run `python3 waybackproxy.py`.
